name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 1 */2 *'

env:
  outPath: "/usr/local/lib/pam/pam_watchid.so"

jobs:
  build:
    strategy:
      matrix:
        version: [macos-15, macos-15-intel, macos-26, macos-26-intel, xcode-27]
        xcode-select: ["xcode", "clt"]
      fail-fast: false

    name: Build (${{ matrix.version }}${{ matrix.xcode-select == 'clt' && ', Command Line Tools' || '' }})

    runs-on: ${{ matrix.version }}

    permissions:
        id-token: write
        contents: read
        attestations: write
        artifact-metadata: write

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      
    - name: Switch to Xcode Command Line Tools
      if: ${{ matrix.xcode-select == 'clt' }}
      run: sudo xcode-select --switch /Library/Developer/CommandLineTools

    - name: Build
      run: make enable

    - name: Get Version
      id: getVersion
      if: ${{ matrix.xcode-select == 'xcode' && matrix.version == 'macos-26' }}
      run: echo "version=$(cat version)" >> "$GITHUB_OUTPUT"

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      if: ${{ matrix.xcode-select == 'xcode' && matrix.version == 'macos-26' }}
      with:
        path: ${{ env.outPath }}.${{ steps.getVersion.outputs.version }}
        if-no-files-found: error
        retention-days: ${{ github.event_name == 'pull_request' && 7 || 90 }}
        archive: false

    - name: Generate artifact attestation
      uses: actions/attest@v4
      if: ${{ matrix.xcode-select == 'xcode' && matrix.version == 'macos-26' && github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      with:
        subject-path: ${{ env.outPath }}.${{ steps.getVersion.outputs.version }}
